- id: typos
  name: typos
  description: "typos-mirror: check the typo error in commit"
  entry: typos
  stages: [pre-commit, pre-merge-commit, pre-push, manual]
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [] # 对所有文件类型进行检查
