- id: typos
  name: typos
  description: "typos-mirror: check the typo error in commit"
  entry: typos
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
